### ISSUE TITLE
paOff, etc

### ISSUE THREAD

**Issue by trmrsh** [HiPERCAM/hcam_finder#16]
Please set 

paOff=76.97
rotcen_x = 1020
rotcen_y = 524

in the hfinder config file

**Comment by StuartLittlefair** [comment]
Have edited the config on the DRPC - it's in ~/.hdriver/config if you want to update your own laptops etc. Making these the default figures in a commit coming up shortly.

**Comment by StuartLittlefair** [comment]
fixed as of https://github.com/HiPERCAM/hcam_finder/commit/d960fb3526b9e738549d4aaf56a88bd8d6932380
