### ISSUE TITLE
ufinder suggested enhancements

### ISSUE THREAD

**Issue by trmrsh** [HiPERCAM/hcam_finder#21]
* hcam-finder version: 1.1.4

Would it be possible to add a faint grey dashed line marking the ULTRACAM dividing line between left & right on ufinder? Idea is to remind people not to put the target too close to it and it serves to indicate the readout direction which is relevant to bleeding of charge from bright stars.

Second possible enhancement: add an indication of the bottom of the chip which is of relevance when setting fields for drift mode when one expects to use the drift mask.

Apologies if this is a mis-use of "issues"

**Comment by StuartLittlefair** [comment]
Cheers tom. 

Excellent suggestions. We already have the dividers for HiPERCAM, should definitely add them for ULTRACAM as well. 

Good idea about indicating the bottom of the chip. Perhaps a thicker line along the bottom?

**Comment by trmrsh** [comment]
yes, a thicker line would do fine

**Comment by StuartLittlefair** [comment]
fixed in https://github.com/HiPERCAM/hcam_finder/commit/acc5c82e04ee6be1a0d1cc5335ab9c1bb45e6371

install V1.1.5 for fixes
