### ISSUE TITLE
usfinder hcam_finder-1.1.5 won't run

### ISSUE THREAD

**Issue by paulkerry1** [HiPERCAM/hcam_finder#22]
* hcam-finder version: 1.1.5
* Python version: 3.7.3
* Operating System: debian linux

### Description
running usfinder from 1.1.5 outputs...

/usr/local/lib/python3.7/dist-packages/ginga/cmap.py:13317: MatplotlibDeprecationWarning: The global colormaps dictionary is no longer considered public API.
  for name in _cm.cmap_d:
Traceback (most recent call last):
  File "/usr/local/bin/usfinder", line 315, in <module>
    main()
  File "/usr/local/bin/usfinder", line 309, in main
    fv = FitsViewer(logger)
  File "/usr/local/bin/usfinder", line 108, in __init__
    self.globals.ipars = InstPars(self)
  File "/usr/local/lib/python3.7/dist-packages/hcam_widgets/uspec.py", line 152, in __init__
    nx, ny, xbfac, ybfac, self.check, hcam=False)
TypeError: __init__() got an unexpected keyword argument 'hcam'

Cheers
Paul.

**Comment by StuartLittlefair** [comment]
Thanks Paul,

This was a bug in the support package `hcam_widgets`. There is a new release of that package (v0.8.1) which fixes this, and a new release of hcam_finders (v1.1.6), whose only change is to insist on hcam_widgets >= 0.8.1

Stu
