### ISSUE TITLE
usfinder problem?

### ISSUE THREAD

**Issue by trmrsh** [HiPERCAM/hcam_finder#23]
hi Stu, have the recent changes to ufinder broken usfinder? See here:

> usfinder
WARNING: AstropyDeprecationWarning: The timefunc function is deprecated and may be removed in a future version.
        Use astroquery.utils.timer.timefunc instead. [astropy.utils.timer]
WARNING: AstropyDeprecationWarning: The timefunc function is deprecated and may be removed in a future version.
        Use astroquery.utils.timer.timefunc instead. [astroquery.vo_conesearch.conesearch]
Traceback (most recent call last):
  File "/home/phsaap/.local/bin/usfinder", line 315, in <module>
    main()
  File "/home/phsaap/.local/bin/usfinder", line 309, in main
    fv = FitsViewer(logger)
  File "/home/phsaap/.local/bin/usfinder", line 108, in __init__
    self.globals.ipars = InstPars(self)
  File "/home/phsaap/.local/lib/python3.8/site-packages/hcam_widgets/uspec.py", line 151, in __init__
    self.wframe = w.Windows(rhs, xs, xsmin, xsmax, ys, ysmin, ysmax,
TypeError: __init__() got an unexpected keyword argument 'hcam'

**Comment by StuartLittlefair** [comment]
There’s a new new version (1.1.6) with a fix for this, but it only works by forcing an upstage of hcam_widgets, so

pip install -U —no-deps hcam_widgets

Should fix

Stuart Littlefair
Dept. of Physics & Astronomy
Univ. of Sheffield, Sheffield, S3 7RH

email: s.littlefair@shef.ac.uk
Phone: +44 114 2224525

**Comment by trmrsh** [comment]
cheers Stu. suspected it might be something like that.
