### ISSUE TITLE
usfinder incorrectly flags window setup as bad

### ISSUE THREAD

**Issue by StuartLittlefair** [HiPERCAM/hcam_finder#25]
number of windows = 3
window 1 = 385, 2,210, 182 [xs,ys,nx,ny]
window 2 = 71,321,640,450
window 3= 641,893,186,128

1x1 binning

"usdriver" is happy with this (gives 4.38 sec cadence for zero exposure delay), "usfinder" is not happy.

**Comment by trmrsh** [comment]
hi stu, similar problem is hfinfer. ! set of quads, with values: 20, 1497, 79, 1155, 118, 538, 395 -- the nx=538 value is highlighted pink for no obvious reason I think

**Comment by StuartLittlefair** [comment]
@trmrsh the `nx=538` value in that case is flagged for good reason. The NGC collects pixel data in chunks before transmission. As a result, to avoid loss of data from frames, the binned x-size must be a multiple of 4.

**Comment by StuartLittlefair** [comment]
A check for the NGC binning issue that should have been removed from the ultra spec windows widget is the cause of the bug in usfinder

**Comment by StuartLittlefair** [comment]
This is fixed in https://github.com/HiPERCAM/hcam_widgets/commit/8c4dfcd9fdeff5082cb56527009af98cc1ae0cc5.

There is a new patch release of hcam_widgets - v0.8.2 and a corresponding release of hcam_finder v1.1.7

**Comment by trmrsh** [comment]
ah, cheers Stu. I had completely forgotten the multiple of 4. Strange that I never managed to click onto a factor of 4 with all my fiddling. Anyway, perhaps it helped spot the usfinder issue for you.

**Comment by StuartLittlefair** [comment]
It did!
