### ISSUE TITLE
hfinder requires astroquery

### ISSUE THREAD

**Issue by paulkerry1** [HiPERCAM/hcam_finder#26]
* hcam-finder version: 1.1.7
* Python version: 3.7.3
* Operating System: Debian 10

### Description

hfinder output...

  File "/usr/local/lib/python3.7/dist-packages/hcam_finder/panstarrs.py", line 5, in <module>
    from astroquery.skyview import SkyView
ModuleNotFoundError: No module named 'astroquery'

Please add astroquery to requirements.txt

Cheers
Paul

**Comment by StuartLittlefair** [comment]
This is fixed in https://github.com/HiPERCAM/hcam_finder/commit/3dfb8c0254aec06cad780e7d9b68d4024c0b5796.

astroquery is an optional requirement, but it was being incorrectly imported in this module
