### ISSUE TITLE
ginga 4.0.1 ImageViewCanvas

### ISSUE THREAD

**Issue by paulkerry1** [HiPERCAM/hcam_finder#35]
* hcam-finder version: 1.2.1
* Python version: 3.9.2
* Operating System: debian 11 amd64

### Description
Updating from ginga-3.4.2 to ginga-4.0.1 breaks ufinder/usfinder/hfinder with...

from ginga.tkw.ImageViewTk import ImageViewCanvas
ImportError: cannot import name 'ImageViewCanvas' from 'ginga.tkw.ImageViewTk' (/usr/local/lib/python3.9/dist-packages/ginga/tkw/ImageViewTk.py)

as it looks like ImageViewCanvas has been deprecated from newer versions of ginga.

Regards
Paul.

**Comment by StuartLittlefair** [comment]
Thanks @paulkerry1 

I’ll look into this on Thursday.

**Comment by StuartLittlefair** [comment]
fixed by #36
